######################################################################
# Automatically generated by qmake (2.01a) lun ago 1 11:26:24 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              qextserialport-master/src \
              qextserialport-master/examples/enumerator \
              qextserialport-master/examples/event \
              qextserialport-master/examples/qespta \
              qextserialport-master/examples/uartassistant
INCLUDEPATH += . \
               qextserialport-master/src \
               qextserialport-master/examples/event \
               qextserialport-master/examples/qespta \
               qextserialport-master/examples/uartassistant

# Input
HEADERS += mainwindow.h \
           qextserialport-master/src/qextserialenumerator.h \
           qextserialport-master/src/qextserialenumerator_p.h \
           qextserialport-master/src/qextserialport.h \
           qextserialport-master/src/qextserialport_global.h \
           qextserialport-master/src/qextserialport_p.h \
           qextserialport-master/examples/event/PortListener.h \
           qextserialport-master/examples/qespta/MainWindow.h \
           qextserialport-master/examples/qespta/MessageWindow.h \
           qextserialport-master/examples/qespta/QespTest.h \
           qextserialport-master/examples/uartassistant/dialog.h \
           qextserialport-master/examples/uartassistant/hled.h
FORMS += mainwindow.ui qextserialport-master/examples/uartassistant/dialog.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           qextserialport-master/src/qextserialenumerator.cpp \
           qextserialport-master/src/qextserialenumerator_linux.cpp \
           qextserialport-master/src/qextserialenumerator_osx.cpp \
           qextserialport-master/src/qextserialenumerator_unix.cpp \
           qextserialport-master/src/qextserialenumerator_win.cpp \
           qextserialport-master/src/qextserialport.cpp \
           qextserialport-master/src/qextserialport_unix.cpp \
           qextserialport-master/src/qextserialport_win.cpp \
           qextserialport-master/examples/enumerator/main.cpp \
           qextserialport-master/examples/event/main.cpp \
           qextserialport-master/examples/event/PortListener.cpp \
           qextserialport-master/examples/qespta/main.cpp \
           qextserialport-master/examples/qespta/MainWindow.cpp \
           qextserialport-master/examples/qespta/MessageWindow.cpp \
           qextserialport-master/examples/qespta/QespTest.cpp \
           qextserialport-master/examples/uartassistant/dialog.cpp \
           qextserialport-master/examples/uartassistant/hled.cpp \
           qextserialport-master/examples/uartassistant/main.cpp
